import Head from "next/head";
import { Col, Row } from "reactstrap";
import SalesChart from "@/panel/components/dashboard/SalesChart";
import TopCards from "@/panel/components/dashboard/TopCards";
import mongoose from "mongoose";
import Product from 'models/Product';
import Contact from "models/Contact";
import Charts from "models/Charts";
import JournalVoucher from "models/JournalVoucher";
import AssetsChart from "@/panel/components/dashboard/AssetsChart";
import { ProSidebarProvider } from "react-pro-sidebar";
import FullLayout from "@/panel/layouts/FullLayout";
import Employees from "models/Employees";

import CreditSalesInvoice from 'models/CreditSalesInvoice';
import SalesInvoice from 'models/SalesInvoice';
import PurchaseInvoice from 'models/PurchaseInvoice';
import DebitNote from 'models/DebitNote';
import CreditNote from 'models/CreditNote';
import ReceiptVoucher from 'models/ReceiptVoucher';
import PaymentVoucher from 'models/PaymentVoucher';
import Expenses from 'models/Expenses';


export default function Home({customer, dbProducts, supplier, employees, dbExpensesVoucher, dbPaymentVoucher, dbReceiptVoucher, dbDebitNote, dbCreditNote, dbPurchaseInvoice, dbSalesInvoice, dbCreditSalesInvoice, dbJournalVoucher, dbCharts }) {

  const noOfCustomers = customer.length;
  const noOfProducts = dbProducts.length;
  const noOfSuppliers = supplier.length;
  const noOfEmployees = employees.length;

  return (
    <>
    <ProSidebarProvider>
    <style jsx global>{`
        footer {
          display: none;
        }
        header {
          display: none;
        }
      `}
    </style>
    <FullLayout>
      <Head>
        <title>Accouting_Software</title>
        <meta name="description" content="Generated by erp system" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/***Top Cards***/}
        <Row>
          <Col sm="6" lg="3">
            <TopCards
              bg="bg-light-danger text-danger"
              href='/panel/businessSetup/productAndServices'
              title="Products"
              subtitle="Total Products"
              amount={noOfProducts}
              icon="bi bi-bag"
            />
          </Col>
          <Col sm="6" lg="3">
            <TopCards
              bg="bg-light-success text-success"
              href='/panel/businessSetup/contactList'
              title="Customer"
              subtitle="Total Customer"
              amount={noOfCustomers}
              icon="bi bi-people"
            />
          </Col>
          <Col sm="6" lg="3">
            <TopCards
              bg="bg-light-warning text-warning"
              href='/panel/businessSetup/contactList'
              title="Supplier"
              subtitle="Total Supplier"
              amount={noOfSuppliers}
              icon="bi bi-basket3"
            />
          </Col>
          <Col sm="6" lg="3">
            <TopCards
              bg="bg-light-info text-into"
              href='/panel/payroll/employees'
              title="Employees"
              subtitle="Total Employee"
              amount={noOfEmployees}
              icon="bi bi-people"
            />
          </Col>
        </Row>
        {/***Sales & Feed***/}
        <Row>
          <Col sm="12" lg="12">
            <SalesChart dbProducts={dbProducts} dbCharts={dbCharts} dbJournalVoucher={dbJournalVoucher} dbExpensesVoucher={dbExpensesVoucher} dbPaymentVoucher={dbPaymentVoucher} dbReceiptVoucher={dbReceiptVoucher} dbDebitNote={dbDebitNote} dbCreditNote={dbCreditNote} dbPurchaseInvoice={dbPurchaseInvoice} dbSalesInvoice={dbSalesInvoice} dbCreditSalesInvoice={dbCreditSalesInvoice}/>
          </Col>
        </Row>

        <Row>
          <Col sm="12" lg="12">
            <AssetsChart dbProducts={dbProducts} dbCharts={dbCharts} dbJournalVoucher={dbJournalVoucher} dbExpensesVoucher={dbExpensesVoucher} dbPaymentVoucher={dbPaymentVoucher} dbReceiptVoucher={dbReceiptVoucher} dbDebitNote={dbDebitNote} dbCreditNote={dbCreditNote} dbPurchaseInvoice={dbPurchaseInvoice} dbSalesInvoice={dbSalesInvoice} dbCreditSalesInvoice={dbCreditSalesInvoice}/>
          </Col>
        </Row>
      </main>
      </FullLayout>
      </ProSidebarProvider>
    </>
  )
}


export async function getServerSideProps() {
  if (!mongoose.connections[0].readyState){
    mongoose.set("strictQuery", false);
    await mongoose.connect(process.env.MONGO_URI)
  }
  let customer = await Contact.find({"type": "Customer"})
  let supplier = await Contact.find({"type": "Supplier"})
  let employees = await Employees.find()
  let dbProducts = await Product.find()
  let dbCharts = await Charts.find()
  let dbJournalVoucher = await JournalVoucher.find()

  let dbCreditSalesInvoice = await CreditSalesInvoice.find()
  let dbSalesInvoice = await SalesInvoice.find()
  let dbPurchaseInvoice = await PurchaseInvoice.find()
  let dbDebitNote = await DebitNote.find()
  let dbCreditNote = await CreditNote.find()
  let dbReceiptVoucher = await ReceiptVoucher.find()
  let dbPaymentVoucher = await PaymentVoucher.find()
  let dbExpensesVoucher = await Expenses.find()
   
  // Pass data to the page via props
  return {
    props: {
      customer: JSON.parse(JSON.stringify(customer)),
      dbProducts: JSON.parse(JSON.stringify(dbProducts)),
      supplier: JSON.parse(JSON.stringify(supplier)),
      employees: JSON.parse(JSON.stringify(employees)),
      dbCharts: JSON.parse(JSON.stringify(dbCharts)),
      dbJournalVoucher: JSON.parse(JSON.stringify(dbJournalVoucher)),

      dbCreditSalesInvoice: JSON.parse(JSON.stringify(dbCreditSalesInvoice)),
      dbSalesInvoice: JSON.parse(JSON.stringify(dbSalesInvoice)),
      dbPurchaseInvoice: JSON.parse(JSON.stringify(dbPurchaseInvoice)),
      dbDebitNote: JSON.parse(JSON.stringify(dbDebitNote)),
      dbCreditNote: JSON.parse(JSON.stringify(dbCreditNote)),
      dbReceiptVoucher: JSON.parse(JSON.stringify(dbReceiptVoucher)),
      dbPaymentVoucher: JSON.parse(JSON.stringify(dbPaymentVoucher)),
      dbExpensesVoucher: JSON.parse(JSON.stringify(dbExpensesVoucher)),
    }
  }
}